defaults: &defaults
  port: 27017

development:
  <<: *defaults
  host: 127.0.0.1
  database: apollo_development

test:
  <<: *defaults
  host: 127.0.0.1
  database: apollo_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: apollo
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
  uri: <%= ENV['MONGOLAB_URI'] %>
